apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 4
>>>>>>> 452a99e03d2ce8b980df0930e56f977c0fc3e64b
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aimvector/python:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "500m"

                    
