apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
